### PR TITLE
Add support for 7 day SLOs

### PR DESCRIPTION
**Pull request by tokheim**
In our org we've been using 7 day SLOs (the last somewhat-common format). This is mostly due to the layer of alerting prometheuses not keeping more than about 10 days of history. The burn rates are maybe a bit opinionated, so open to suggestions. Its based on playing around with https://wpjunior.github.io/multi-burn-rate-calculator/.

### CODE REVIEW

**Comment by slok** [comment]
Hi @tokheim!

Thanks for this contribution. To be honest, I like the idea, seriously, but I'm not 100% sure about merging this, not because of how is the PR, that as a first read its awesome, its because every person/company could have a different use case and opinion, Sloth's goal is to have safe defaults and easy to use.

I agree to support `28` day time windows along with the default `30` day, because
- Is pretty similar to the 30 days.
- Commonly used.
- Already been proven that it works perfectly.

I would like to think about it a bit before rushing.

Have you tested the fork in your company? could you give me more data of examples and how is working?

**Comment by tokheim** [comment]
Thanks, I had a bit the same feeling, there's no well defined best practice from the sre handbook on 7 day SLO burn rates, and while the values I picked are sensible, I could easily see someone argue for something else.

I haven't tested the fork (just discovered your project on Friday), but we have experience from managing the same recording rules. Overall I would say that a 7d slo is a lot harder to maintain, it demands more from the on-duty team, both in that lower burn rates trigger pages, and that they have much less time to react to the problem before error budget is consumed. Still it forces frequent reviews of the SLO, allowing dev team to adjust priorities to resiliency fixes, so its good for maintaining a 30d SLA.

My main concern for a 30d SLO would be that we currently don't store 30d of data in the prometheuses closest to the applications. We'd like to keep them as slim as possible. Moving the alerts to something like thanos (where we'd keep more historical data) would add potentially new error sources that could break alerting.

One other approach I considered was to move https://github.com/slok/sloth/pull/188/files#diff-2d1ca6e6370d2c111dc2537b20802e4c672a95f7a1ddf8645206f144330b07c5R65 out to some external config file, so sloth could offer sensible defaults that just work, but still allow anyone to override alerting windows, burn rates and SLO periods. I very much understand how you'd want sloth to just follow best practices out of the box, but I could see benefit in a bit more flexibility for advanced users. If that approach sounds more appealing, I think I'd need a bit of guidance on what the CLI should be.

**Comment by slok** [comment]
Thanks for the replay and the information!

What you say about moving to a config file I considered when I refactored all the alerting thingy. The idea was to add the 28-day window but be prepared to extend it easily. I didn't take that path because I wasn't sure if people will need this (I'm very cautious adding features that add complexity and are not used by the users).


Anyhow, the time has come and is time to have this feature, Sloth growth the user base enough to have custom/advanced needs), would be a good feature to have this for 3 reasons:

- Allow advanced users to adapt Sloth to its company/team.
- Test and research easily new windows (that could end on Sloth defaults).
- People share the windows that work for them with others that have the same context (company, services, quantity...).

For example, a person could have 3 Sloth instances running in Kubernetes, all the same except the windows configuration, and use label selectors (that Sloth allows this already) to select the SLOs targeted for these experimental windows, and check them afterwards by comparing (when one triggers alerts when the other not...).

I'm thinking about this spec:

```yaml
version: "alertWindows/v1"

fullWindow: 30d

page:
  quick:
    errorBudgetsPercent: 2
    shortWindow: 5m
    longWindow: 1h
  slow:
    errorBudgetPercent: 5
    shortWindow: 30m
    longWindow: 6h
ticket:
  quick:
    errorBudgetPercent: 10
    shortWindow: 2h
    longWindow: 1d
  slow:
    errorBudgetPercent: 10
    shortWindow: 6h
    longWindow: 3d
```

What do you think about this spec?

I almost have the first draft implementation. But I need to think about the user experience when using it (flags, deprecation or not, and that stuff).

Sadly by implementing this I would need to close your PR with all your work :( However, you have been the main trigger for this feature, so many thanks. Also, I would be very grateful if you could test it and see how it works when I have it done (hope this week).

**Comment by tokheim** [comment]
Don't worry about closing my pull request. I knew there was a risk to not creating an issue, just wanted to do all I could to speed up my own adoption of sloth. Really appreciate you looking into this, and will happily test your PR, or help you out in any other way.

The config seems pretty straight forward. Instead of `fullWindow` I'd maybe call it `sloPeriod`. A multi-rate ticket window maybe isn't that common (i.e. not part of recommended params in https://sre.google/workbook/alerting-on-slos/), so wondering if you can/should be able to turn off one of the windows. I guess with error budget of quick window being the same as the slow its sort of disabled already?

One thing I was planning to bring up in a different issue is the optimization [done here](https://github.com/slok/sloth/blob/main/internal/prometheus/recording_rules.go#L138). I think this alters the interpretation of the SLO and maybe should be overridable in a config. In [openSLO](https://github.com/OpenSLO/OpenSLO) terms it seems to set the `budgetingMethod` to `timeSlices`. Basically it doesn't take into account the usage/number of requests in each timeslice, so any timeperiod is deemed equally valuable. This [Grafana blog post](https://grafana.com/blog/2021/05/17/grafana-labs-at-sloconf-all-the-details/) gives a description of the topic. Happy to deal with that in a different issue, if you want to get the basic config up first.

**Pull request closed without merging**
