### PR TITLE
# Sample job that allows you to download the generated files as Artif…

### PR DESCRIPTION
**Pull request by taivo123**
Sample job that allows you to download the generated files as Artifacts from the Github Actions page

### CODE REVIEW

**Comment by slok** [comment]
Hi @taivo123 

Thanks for the PR!

I understand what it does, however, I don't know what is the purpose of this. What is this for and what is your use case?

Best

**Comment by taivo123** [comment]
An example for people who can not or want not to run cli in their pc or just want CICD get-started guide :) you can delete the PR no problem, just thought to share because our team needed this.
________________________________

**Comment by slok** [comment]
Understood! I never thought about this use case, I like the idea!

**Comment by slok** [comment]
Hi @taivo123! Sorry for the delay, I'll add this also to the documentation :)

**Pull request merged**
