### PR TITLE
Add alerting windows spec and use these to customize the alerts for advanced users

### PR DESCRIPTION
**Pull request by slok**
This PR adds support for customizing SLO period windows.

It has a new spec that the users can use to decide how the SLO period windows should be. An example of the most common used SLO period (30d) that Sloth has by default, would be declared like this:

```yaml
apiVersion: "sloth.slok.dev/v1"
kind: "AlertWindows"
spec:
  sloPeriod: 30d
  page:
    quick:
      errorBudgetPercent: 2
      shortWindow: 5m
      longWindow: 1h
    slow:
      errorBudgetPercent: 5
      shortWindow: 30m
      longWindow: 6h
  ticket:
    quick:
      errorBudgetPercent: 10
      shortWindow: 2h
      longWindow: 1d
    slow:
      errorBudgetPercent: 10
      shortWindow: 6h
      longWindow: 3d

```

By default, Sloth continues supporting `28d` and `30d` SLO periods.

Also added `--slo-period-windows-path` flag to load custom SLO period windows from a directory.

## BREAKING
- `--window-days` has been renamed to `--default-slo-period`.
- Removed `-w` short flag for  `--window-days`.

### CODE REVIEW

**Comment by tokheim** [comment]
Thanks for this! Will try to provide some feedback later in the week

**Comment by slok** [comment]
Thanks @tokheim!

I'll merge tomorrow into main, you can grab that release (all main merges release a docker image).

**Comment by slok** [comment]
@tokheim Here you have more information:

- Release: `docker pull ghcr.io/slok/sloth:d4c23e61090bc44d37b3b218d388445ddc7b4b35`
- Docs: https://sloth.dev/usage/slo-period-windows

Thanks!

**Comment by tokheim** [comment]
Thanks @slok . I tried up the image, and prepared a pull request #204 , but it seems like there is a bug with the kubernetes controller. I added some details on how to reproduce the problem there. Will have a look if I can find some obvious reason for the problem but wanted to give you an early heads up.

**Comment by slok** [comment]
Thanks for all the work @tokheim! We can continue the thread in your PR.

**Pull request merged**
