### PR TITLE
Helm window config

### PR DESCRIPTION
**Pull request by tokheim**
Preparing a pull request for helm config for the [custom slo windows](https://sloth.dev/usage/slo-period-windows)

### CODE REVIEW

**Comment by slok** [comment]
That error is returned by Sloth as a safety mechanism to avoid duplicated window configurations. Is like if the 7d spec is loaded multiple times

**Comment by slok** [comment]
If I run sloth from Local against a cluster it works:

```
$ ls ./examples/windows/
7d.yaml  custom-30d.yaml

$ go run ./cmd/sloth/ kubernetes-controller --kube-local --slo-period-windows-path ./examples/windows/ --default-slo-period=7d
INFO[0000] SLI plugins loaded                            plugins=0 svc=storage.FileSLIPlugin version=dev window=7d
INFO[0000] Using custom slo period windows catalog       svc=alert.WindowsRepo version=dev window=7d
INFO[0000] SLO period windows loaded                     svc=alert.WindowsRepo version=dev window=7d windows=2
INFO[0000] Loading Kubernetes configuration...           version=dev
INFO[0000] Kubernetes controller running                 version=dev window=7d
INFO[0000] starting controller                           controller-id=sloth lib=kooper service=kooper.controller version=dev window=7d
INFO[0000] Hot-reload http server listening              addr=":8082" version=dev window=7d
INFO[0000] OS signals listener started                   version=dev window=7d
INFO[0000] Metrics http server listening                 addr=":8081" version=dev window=7d
INFO[0000] Hot-reload manager running                    version=dev window=7d
...
```

**Comment by tokheim** [comment]
I really couldn't find any problems with your code. But it looks like I maybe ran into the issue described in https://stackoverflow.com/questions/62776362/k8s-configmap-mounted-inside-symbolic-link-to-data-directory.

Basically if I add a busybox sidecar to inspect the container, then this is what I see
```
$ kubectl exec -it sloth-75d456db78-qvlc9 -c busy -- ls -lah /windows
total 12
drwxrwxrwx    3 root     root        4.0K Nov 11 23:48 .
drwxr-xr-x    1 root     root        4.0K Nov 11 23:48 ..
drwxr-xr-x    2 root     root        4.0K Nov 11 23:48 ..2021_11_11_23_48_15.272910254
lrwxrwxrwx    1 root     root          31 Nov 11 23:48 ..data -> ..2021_11_11_23_48_15.272910254
lrwxrwxrwx    1 root     root          18 Nov 11 23:48 window.yaml -> ..data/window.yaml

$ kubectl exec -it sloth-75d456db78-qvlc9 -c busy -- ls -lah /windows/..2021_11_11_23_48_15.272910254
total 12
drwxr-xr-x    2 root     root        4.0K Nov 11 23:48 .
drwxrwxrwx    3 root     root        4.0K Nov 11 23:48 ..
-rw-r--r--    1 root     root         421 Nov 11 23:48 window.yaml
```

Never heard about this behavior before, but I guess the `walkdir` function will then traverse the subdirectory. I should be able to work around the problem with the hack proposed in the post, though it seems like a problem that other non-helm users might run into. Will experiment a bit tomorrow.

**Comment by slok** [comment]
First of all, sorry for closing the PR, when I referenced this PR from the other PR with the prefix `Fixes`, Github automatically closed :sweat_smile: 

Indeed, those symlinks are the ones causing this behaviour, it makes total sense to avoid those hacks, is a very common use case and easy to fall into the trap. So... I implemented #205 

Please try this new release: `docker pull ghcr.io/slok/sloth:a78476d371802a7806859fbd4dc33c4ea2285415`.

**Comment by tokheim** [comment]
Thanks for the very rapid response! Everything seems to be working as intended now. I get the new warning that you added, so this was definitely the cause. All the recording rules seem correctly generated as well, so we will definitely be switching our manually generated recording rules to your operator. Thanks again.

I'll clean up this branch a bit and fix the ci failure. Is there any chance we could get a tagged release or would you want to see this running a bit more in the wild first?

**Comment by slok** [comment]
Awesome! :tada: :metal: 

Yes, I'll publish a new release during this weekend, tops Monday.

Many thanks!

**Comment by tokheim** [comment]
I fixed and added a couple of tests. Will bump tag, chart version and submit PR once new image is ready.

Let me know if you have any opinion on variables, or anything else you'd want me to change.

**Comment by slok** [comment]
Hey @tokheim! I see everything ok, Could you submit the PR, and then we create a new release? I say this because some people could use kustomize or the raw with the Sloth tagged version and should match the manifests. So I propose:

- Create the PR, merge
- Change the helm image version with the new tag version (and generate raw manifests).
- Publish release.

What do you think?

**Comment by tokheim** [comment]
Sure, I guess I should leave the chart version as-is until image tag gets updated in the chart too then.

**Comment by slok** [comment]
Hi @tokheim!

I released a new Sloth version ([v0.9.0](https://github.com/slok/sloth/releases/tag/v0.9.0)) and also a new chart version ([v0.4.0](https://github.com/slok/sloth/releases/tag/sloth-helm-chart-0.4.0)). So, everything should be ready to be used!

Many thanks for everything!

**Comment by tokheim** [comment]
Thanks, seems to be working great...

**Pull request merged**
