### PR TITLE
Ignore sloth_window in prometheus alerts

### PR DESCRIPTION
**Pull request by Limess**
This prevents alerts resolving and re-firing when different windows fire.

Implemented using the suggestion from @tokheim in #240.
Fixes https://github.com/slok/sloth/issues/240

### CODE REVIEW

**Comment by slok** [comment]
Hi!

First of all @Limess Thanks for the PR!! and second... sorry to @tokheim for taking so long to keep the ball rolling on this enhancement.

Regarding the PR, I'm into adding this, so very happy to see it! :rocket: An small comment regarding the query, what do you think about this simplification?

From this:
```
(
     (
          max without (sloth_window) (slo:sli_error:ratio_rate5m{sloth_id="workshop-burning-2x-jitter-10"}) > ...
          and 
          max without (sloth_window) (slo:sli_error:ratio_rate1h{sloth_id="workshop-burning-2x-jitter-10"}) > ...
      )
      or ignoring (sloth_window)
      (
          max without (sloth_window) (slo:sli_error:ratio_rate30m{sloth_id="workshop-burning-2x-jitter-10"}) > ...
          and 
          max without (sloth_window) (slo:sli_error:ratio_rate6h{sloth_id="workshop-burning-2x-jitter-10"}) > ...
      )
)
```

to:

```
max without (sloth_window) (
     (
          (slo:sli_error:ratio_rate5m{sloth_id="workshop-burning-2x-jitter-10"}) > ...
          and ignoring (sloth_window)
          (slo:sli_error:ratio_rate1h{sloth_id="workshop-burning-2x-jitter-10"}) > ...
      )
      or ignoring (sloth_window)
      (
          (slo:sli_error:ratio_rate30m{sloth_id="workshop-burning-2x-jitter-10"}) > ...
          and ignoring (sloth_window)
          (slo:sli_error:ratio_rate6h{sloth_id="workshop-burning-2x-jitter-10"}) > ...
      )
)
```

From my point of view the last one would be like "Get me the alert, and now, once I have it, drop this specific label, because I don't want it".

Let me know your thoughts on this. Thanks!

**Comment by tokheim** [comment]
Personally I favor the readability of the suggestion in PR. It normalizes the metrics, and then there is no fuzz when joining them together with and/or. Still I see that as quite a subjective preference, and since its sort of part of the internal logic of the library, I think probably your opinion matters more then @slok. One thing that could be an important factor is the performance of the query. Did some very unscientific tests and couldn't see any noticeable difference though.

No worries @slok, even with a few re-firings I'm super happy with sloth. Thanks @Limess for looking into the issue!

**Comment by Limess** [comment]
I updated the branch to fix the test failures (inconsistency in window spacing). Let me know if you would like to go ahead with your alternative or not, it'd be great to get this in as it's causing a small amount of confusion when introducing Sloth in our org right now.

**Comment by slok** [comment]
Forget about my comment, although I prefer what I propose, I don't have a strong opinion and @tokheim was the starter of this problem and approach, so let's go with his approach :)

**Comment by slok** [comment]
The integration tests are failing because you removed the `ignore window` also on the optimized SLI recording rules ([e.g](https://github.com/slok/sloth/pull/295/files#diff-a896bb9413f81c23808f586838022f9dd1f143f311a2b8e9327a7ae703e06dd7L96)) instead of only removing them from the alerting rules.

**Comment by Limess** [comment]
Thanks, they run locally aside from some warns about missing binaries.

**Comment by Limess** [comment]
Sorry about the multiple iterations - I should have found this sooner <https://github.com/slok/sloth/blob/main/CONTRIBUTING.md>! 

It's a little confusing that the way of running the k8s/CLI tests locally is using the CI commands, and that `make integration` doesn't seem to find the binaries (I assume it needs the binary and kube config mounting and setting as env vars in the docker container).

I've been through them individually and copied actual into the assertions now, and the `make ci-integration-k8s` and `make ci-integration-cli` now pass.

**Comment by slok** [comment]
No worries, the CI thing is because these executions are run without docker and normally CI tests are mostly run in CI and not on local (except when big changes are made, like affecting the resulting rules).

**Comment by slok** [comment]
I'll try taking a look this week however I'll be in Valencia in the Kubecon so maybe it's delayed until next week! :sweat: many thanks for all the effort @Limess :top:

**Review by slok — APPROVED** [review]
Lets gooooo :rocket: :shipit: 

Many thanks @Limess and @tokheim!

**Comment by slok** [comment]
@Limess @tokheim Could you test this with `ghcr.io/slok/sloth:2de193572284e36189fe78ab33beb7e2b339b0f8` image and after some days give me feedback of the outcome? It's a big change so the more we test the better before cutting a new release.

Many thanks!

**Comment by Limess** [comment]
Thanks for merging!

I've tested this on our alerts and it looks fine, no noticable change in burn rates or anything.

We're only using sloth to generate prometheus config as a build step, we're not running anything live in kubernetes, so can't help there.

**Comment by Limess** [comment]
Hey @slok, any chance that we could get a stable release with this change? We've been running the alerts in productions for a while now and they fix the issue for us.

**Comment by slok** [comment]
Hi @Limess!

Sorry for the delay.

I'll try sorting this in the nex 2t weeks (I'll check dependency upgrades, helm chart PRs...).

Thanks.

**Pull request merged**
